### ISSUE TITLE
Is this feature still being worked on?

### ISSUE THREAD

**Issue by Handrail9** [thunderbird/linux-sys-tray#3]
The repo has been quiet for ~3 months and I haven't seen any updates from team members / contributors on the forum post.

**Comment by hellsworth** [comment]
We added the foundational icon that just has one quit function. That lays the groundwork for now adding useful features. We want to continue working on it and we will, but right now we're focusing on EWS as the priority. Then we can get back to working on this fun project :)

**Comment by Handrail9** [comment]
@hellsworth Thats fair, I appreciate the response! The way I read the forum post was that the feature was coming very soon but I understand now that its a bit lower on the priority list. Still happy to hear its coming soon! :)

**Comment by hellsworth** [comment]
You can go try it out now if you'd like in [Thunderbird Beta](https://www.thunderbird.net/en-US/download/beta/) :smiley:

**Comment by filipesaraiva** [comment]
Well, I am very sorry to hear that this long awaited feature by us Linux users (because Windows and OSX have this feature implemented several years ago) is once again in low priority.

We, Linux users, just want to hide Thunderbird from our taskbar and keep it running in the background, with easy access via the system tray. We don't care this time about very advanced systray features and so on... it can be implemented in the future. For now, since the entire life of Thunderbird this feature was not implemented, we would be happy with a simple systray feature - more than enough for the current lack of systray support on Linux.

Please, just apply the [systray patches](https://github.com/Betterbird/thunderbird-patches/tree/main/128/features) from Betterbird. See the files numbered by 12 and 13. This will be enough for most of us.
